[package]
name = "rforth"
version = "0.1.0"
authors = ["Steen Larsen <sla@keycore.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
maplit = "1.0.2"
strum = "0.20.0"
strum_macros = "0.20.0"
